#!/bin/zsh

# this function returns location and other information from an ip address
whoip () {
	echo checking ip address: $1
	curl http://ipinfo.io/$1
}

journalpub () {

  ORIG=$(pwd)
  cd ~/Journal > /dev/null
  find . -name "*.txt" | tar -czvf journals.tar.gz -T -
  gpg -o journals-safe.tar.gz.gpg -e -r acbilson@gmail.com journals.tar.gz
  mv -f journals-safe.tar.gz.gpg ~/OneDrive/Documents/Journals/journals-safe.tar.gz.gpg
  rm journals.tar.gz
  cd "$ORIG" > /dev/null

  # to decrypt:
  # gpg --decrypt ~/OneDrive/Documents/Journals/journals-safe.tar.gz.gpg > journals.tar.gz
  # mkdir decrypted_files
  # tar -xvf journals.tar.gz -C decrypted_files
}

# prints out last year's memoir
lastyear () {

  # gets today's date, subtracts year by one, and removes leading zero (if single-digit date)
  LAST_YEAR=$(date -v -1y '+%d %B %Y' | sed 's/^0//')

  # retrieves the memoir entry from last year (if it exists)
  ENTRY=$(/usr/local/bin/rg -iNI " $LAST_YEAR" -A 4 -B 1 ~/journal)

  if [ ! "$ENTRY" = '' ]; then
    echo "$ENTRY"
  fi
}



pyclean () {
  find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
}

cd () {
  builtin cd "$1" && ls
}
