#!/bin/zsh

# # # # # # # #
# FUNCTIONS
# # # # # # # #

## securely publishes sensitive files to OneDrive
function secretpub () {

  DEST=/Users/Shared/OneDrive/Software/Secure
  ORIG=$(pwd)
  mkdir ~/secret_tmp

  # stores ssh keys and config
  find ~/.ssh -type f ! -iname 'known_hosts' | tar -czvf ssh.tar.gz -T -
  gpg -o ssh-safe.tar.gz.gpg -e -r acbilson@gmail.com ssh.tar.gz
  mv -f ssh-safe.tar.gz.gpg $DEST/
}

## securely publishes my journal entries to OneDrive
function journalpub () {

  DEST=/Users/Shared/OneDrive/Software/Secure
  ORIG=$(pwd)
  cd ~/journal > /dev/null
  find . -name "*.txt" | tar -czvf journals.tar.gz -T -
  gpg -o journals-safe.tar.gz.gpg -e -r acbilson@gmail.com journals.tar.gz
  mv -f journals-safe.tar.gz.gpg $DEST/
  rm journals.tar.gz
  cd "$ORIG" > /dev/null
}

function journalextract () {

  DEST=/Users/Shared/OneDrive/Software/Secure
  ORIG=$(pwd)
  cd ~/journal > /dev/null
  gpg --decrypt $DEST/journals-safe.tar.gz.gpg > journals.tar.gz
  tar -xf journals.tar.gz
  rm journals.tar.gz
  cd "$ORIG" > /dev/null
}

## prints out last year's memoir
function lastyear () {

  # gets today's date, subtracts year by one, and removes leading zero (if single-digit date)
  LAST_YEAR=$(date -v -1y '+%d %B %Y' | sed 's/^0//')

  # retrieves the memoir entry from last year (if it exists)
  ENTRY=$(/usr/local/bin/rg -iNI " $LAST_YEAR" -A 4 -B 1 ~/journal)

  if [ ! "$ENTRY" = '' ]; then
    echo "$ENTRY"
  fi
}

## overrides cd to print contents after execution
function cd () {
  builtin cd "$1" && ls
}

# # # # # # # #
# ALIASES
# # # # # # # #

# to temporarily bypass an alias that overwrites the original
# prepend '\'. e.g. >\ls

# Command aliases
alias ls="exa -l"
alias ps="ps -eo pid,euser,stime,cmd --forest"
alias ports="netstat -lt"

# Location aliases
alias blog="~/source/alexbilson.dev"
alias content="~/source/chaos-content"
alias theme="~/source/chaos-theme"

# Other aliases
alias jour="vim ~/journal/memoir_2021.txt"

#alias pil="sudo ssh -i ~/.ssh/pi_rsa -p 3492 pi@raspberrypi.local"
#alias pir="sudo ssh -i ~/.ssh/pi_rsa -p 3492 pi@216.80.113.4"
