#!/bin/zsh

# # # # # # # #
# FUNCTIONS
# # # # # # # #

# this function returns location and other information from an ip address
whoip () {
	echo checking ip address: $1
	curl http://ipinfo.io/$1
}

journalpub () {

  ORIG=$(pwd)
  cd ~/Journal > /dev/null
  find . -name "*.txt" | tar -czvf journals.tar.gz -T -
  gpg -o journals-safe.tar.gz.gpg -e -r acbilson@gmail.com journals.tar.gz
  mv -f journals-safe.tar.gz.gpg ~/OneDrive/Documents/Journals/journals-safe.tar.gz.gpg
  rm journals.tar.gz
  cd "$ORIG" > /dev/null

  # to decrypt:
  # gpg --decrypt ~/OneDrive/Documents/Journals/journals-safe.tar.gz.gpg > journals.tar.gz
  # mkdir decrypted_files
  # tar -xvf journals.tar.gz -C decrypted_files
}

# prints out last year's memoir
lastyear () {

  # gets today's date, subtracts year by one, and removes leading zero (if single-digit date)
  LAST_YEAR=$(date -v -1y '+%d %B %Y' | sed 's/^0//')

  # retrieves the memoir entry from last year (if it exists)
  ENTRY=$(/usr/local/bin/rg -iNI " $LAST_YEAR" -A 4 -B 1 ~/journal)

  if [ ! "$ENTRY" = '' ]; then
    echo "$ENTRY"
  fi
}

pyclean () {
  find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
}

cd () {
  builtin cd "$1" && ls
}

# # # # # # # #
# ALIASES
# # # # # # # #

# to temporarily bypass an alias that overwrites the original
# prepend '\'. e.g. >\ls

alias ls="exa -l"

# can now use ssh web b/c/o .sshconfig
#alias pil="sudo ssh -i ~/.ssh/pi_rsa -p 3492 pi@raspberrypi.local"
#alias pir="sudo ssh -i ~/.ssh/pi_rsa -p 3492 pi@216.80.113.4"

# decided to remove mosh
# alias mosh_web="mosh -p 3492 --ssh=\"ssh -p 3492\" pi@raspberrypi.local"

# LINUX ONLY
#alias ls="ls -lAhF --group-directories-first --time-style=+'%Y/%m/%d %k:%M' --color=auto"

# also consider pstree -p
alias ps="ps -eo pid,euser,stime,cmd --forest"
alias ports="netstat -lt"

# website specific
alias weblog="cat /var/log/nginx/simple-access.log /var/log/nginx/simple-access.log.1 | grep -v '216.80.113.4' | awk -F '|' '{print \$2,\$4,\$5}' | sort -k 4 | uniq"
alias apthistory="cat /var/log/apt/history.log"

export DOCKER_SHELL=/bin/bash

# Docker functions
docker-shell () {
  if [ "$1" = "" ]; then
    LATEST_CONTAINER=$(dk ps -l --format "{{.ID}}")
    docker exec -it "$LATEST_CONTAINER" ${DOCKER_SHELL}
  fi
  docker exec -it "$1" ${DOCKER_SHELL}
}
docker-root-shell () {
  if [ "$1" = "" ]; then
    LATEST_CONTAINER=$(dk ps -l --format "{{.ID}}")
    docker exec -it --user root "$LATEST_CONTAINER" ${DOCKER_SHELL}
  fi
  docker exec -it --user root "$1" ${DOCKER_SHELL}
}

# Docker aliases
alias dk="docker"
alias dkcp="docker-compose"
alias dkc="docker container"
alias dkl="docker logs"
alias dki="docker images"
alias dksh="docker-shell"
alias dkrsh="docker-root-shell"

# Location aliases
alias blog="~/source/alexbilson.dev"
alias content="~/source/chaos-content"
alias theme="~/source/chaos-theme"

# Other aliases
alias make="make -B"
alias jour="vim ~/journal/memoir_2021.txt"

# todo.sh aliases
alias todo="todo.sh"
