#!/bin/zsh

# # # # # # # #
# FUNCTIONS
# # # # # # # #

## returns location and other information from an ip address
function whoip () {
	echo checking ip address: $1
	curl http://ipinfo.io/$1
}

## checks if a command exists
function cmd_exists () { type -p "$1" > /dev/null || return 1 }

## removes python cache files
pyclean () {
  find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
}

## lists all custom functions and their descriptions
function list_functions {
  rg -N '^## ' -A 1
}

# # # # # # # #
# ALIASES
# # # # # # # #

# to temporarily bypass an alias that overwrites the original
# prepend '\'. e.g. >\ls

alias make="make -B"
alias todo="todo.sh"

# # # # # # # #
# ALIASES
# # # # # # # #

export DOCKER_SHELL=/bin/bash

# Docker functions
docker-shell () {
  if [ "$1" = "" ]; then
    LATEST_CONTAINER=$(dk ps -l --format "{{.ID}}")
    docker exec -it "$LATEST_CONTAINER" ${DOCKER_SHELL}
  fi
  docker exec -it "$1" ${DOCKER_SHELL}
}

docker-root-shell () {
  if [ "$1" = "" ]; then
    LATEST_CONTAINER=$(dk ps -l --format "{{.ID}}")
    docker exec -it --user root "$LATEST_CONTAINER" ${DOCKER_SHELL}
  fi
  docker exec -it --user root "$1" ${DOCKER_SHELL}
}

# Docker aliases
alias dk="docker"
alias dkcp="docker-compose"
alias dkc="docker container"
alias dkl="docker logs"
alias dki="docker images"
alias dksh="docker-shell"
alias dkrsh="docker-root-shell"
