# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# appends history between sessions
setopt appendhistory

# move to folder without appending 'cd'
setopt autocd

# extends glob expansion, which makes navigation easier
setopt extendedglob

# sends error when no match occurs
setopt nomatch

# turns off beeping on error
unsetopt beep

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/abilson/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Begin custom configurations from optional files

FILES=(.zsh_theme .zsh_common .zsh_module .zsh_settings)

function load_file () {
  if [[ ! -f ~/"$1" ]]; then
    echo "~/$1 does not exist. Skipping..."
  else
    . ~/"$1"
  fi
}

for file in $FILES; do
  load_file "$file"
done

# End custom configurations from optional files
