# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# appends history between sessions
setopt appendhistory

# move to folder without appending 'cd'
setopt autocd

# extends glob expansion, which makes navigation easier
setopt extendedglob

# sends error when no match occurs
setopt nomatch

# turns off beeping on error
unsetopt beep

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/abilson/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Begin custom configurations from optional files

FILES=(.zsh_common .zsh_module .zsh_theme)

function load_file () {
  if [[ ! -f ~/"$1" ]]; then
    echo "~/$1 does not exist. Skipping..."
  else
    . ~/"$1"
  fi
}

for file in $FILES; do
  load_file "$file"
done

# ssh keys
if [ -f ~/.ssh/git_rsa ]; then
    ssh-add ~/.ssh/git_rsa
fi

# auto loads ssh keys (if keychain is available)
if [ -x "$(command -v keychain)" ]; then
	eval `keychain --agents ssh --eval git_rsa`
fi

# sets editor to vim (if vim exists)
if [ -x "$(command -v vim)" ]; then
	export EDITOR=/usr/bin/vim
fi

# End custom configurations from optional files
# Begin custom paths
export PATH="$PATH:$HOME/.local/bin"
# End custom paths

# Begin Docker configurations

# bind the C:/ drive to a new mount point
# WINDOWS ONLY
#export DOCKER_HOST=tcp://localhost:2375
#mkdir -p /c && sudo /bin/mount --bind /mnt/c /c

# End Docker configurations
